/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ViteImport } from './routes/vite'
import { Route as ReactImport } from './routes/react'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ViteRoute = ViteImport.update({
  path: '/vite',
  getParentRoute: () => rootRoute,
} as any)

const ReactRoute = ReactImport.update({
  path: '/react',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/react': {
      preLoaderRoute: typeof ReactImport
      parentRoute: typeof rootRoute
    }
    '/vite': {
      preLoaderRoute: typeof ViteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ReactRoute,
  ViteRoute,
])

/* prettier-ignore-end */
